name: Run Tests with ExtentReports

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Maven Clean
      run: mvn clean

    - name: Verify Configuration report-config
      run: ls -al src/main/resources/report_config/html-config.xml

    - name: Verify Configuration extent properties
      run: ls -al src/main/resources/extent.properties

    - name: Run Tests with debug
      run: mvn test -X -Dtest=LoginAndPurchaseTestCase