name: Run Tests

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Maven Clean
        run: mvn clean

      - name: Verify Configuration report-config
        run: ls -al src/main/resources/report_config/html-config.xml

      - name: Verify Configuration extent properties
        run: ls -al src/main/resources/extent.properties

      # Instalar o Google Chrome
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb

      # Install ChromeDriver
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | sed 's/\..*//')
          CHROMEDRIVER_VERSION=$(curl -sSL "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          echo "ChromeDriver Version: $CHROMEDRIVER_VERSION"
          wget https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.204/linux64/chromedriver-linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Chrome Version
        run: google-chrome --version

      # Rodar os testes com debug
      - name: Run Tests with debug
        run: mvn test -X -Dtest=LoginAndPurchaseTestCase
